use std::{ffi::OsStr, io::Write, path::PathBuf, sync::Arc};

use anyhow::Context as _;
use futures::TryFutureExt;
use gpui::{BackgroundExecutor, FontWeight, Image, ImageFormat, ImageSource, Task, img};
use paths::mermaid_cache_dir;
use sha2::{Digest, Sha256};
use smol::{fs, process::Command};
use theme::Appearance;
use ui::{
    ActiveTheme, App, CommonAnimationExt, Context, Icon, IconName, IconSize, IntoElement, Label,
    LabelCommon, ParentElement, RenderOnce, SharedString, Styled, Window, div, h_flex, v_flex,
};

#[derive(IntoElement)]
pub struct MermaidDiagram {
    source: SharedString,
}

impl MermaidDiagram {
    pub fn new(source: impl Into<SharedString>) -> Self {
        Self {
            source: source.into(),
        }
    }
}

impl RenderOnce for MermaidDiagram {
    fn render(self, window: &mut Window, cx: &mut App) -> impl IntoElement {
        let state = window.use_state(cx, |_, cx| {
            MermaidRenderState::start(self.source.clone(), cx)
        });

        match state.read(cx) {
            MermaidRenderState::Started(_) => h_flex()
                .items_center()
                .py_4()
                .gap_1()
                .child(Icon::new(IconName::LoadCircle).with_rotate_animation(2))
                .child(Label::new("Rendering Mermaid diagram...")),

            MermaidRenderState::Finished(Ok(image)) => {
                div().child(img(ImageSource::Image(image.clone())))
            }

            MermaidRenderState::Finished(Err(error)) => h_flex()
                .items_baseline()
                .p_4()
                .gap_1()
                .text_color(cx.theme().status().error)
                .bg(cx.theme().status().error_background)
                .rounded_sm()
                .child(Icon::new(IconName::XCircle).size(IconSize::Medium))
                .child(
                    v_flex()
                        .gap_2()
                        .child(
                            Label::new("Failed to render Mermaid diagram").weight(FontWeight::BOLD),
                        )
                        .child(Label::new(format!("{error:#}"))),
                ),
        }
    }
}

enum MermaidRenderState {
    Started(#[allow(unused)] Task<()>),
    Finished(Result<Arc<Image>, anyhow::Error>),
}

impl MermaidRenderState {
    fn start(source: SharedString, cx: &mut Context<Self>) -> Self {
        let appearance = cx.theme().appearance;
        let executor = cx.background_executor().clone();

        Self::Started(cx.spawn(async move |this, cx| {
            let result = render_mermaid(source, appearance, executor).await;
            _ = this.update(cx, |this, cx| {
                *this = Self::Finished(result);
                cx.notify();
            });
        }))
    }
}

trait AppearanceExt {
    fn cache_file_affix(self) -> &'static str;
    fn mermaid_theme(self) -> &'static str;
}

impl AppearanceExt for Appearance {
    fn cache_file_affix(self) -> &'static str {
        match self {
            Self::Light => "light",
            Self::Dark => "dark",
        }
    }

    fn mermaid_theme(self) -> &'static str {
        match self {
            Self::Light => "default",
            Self::Dark => "dark",
        }
    }
}

async fn render_mermaid(
    source: SharedString,
    appearance: Appearance,
    executor: BackgroundExecutor,
) -> anyhow::Result<Arc<Image>> {
    let path = cache_path(&source, appearance);
    let bytes = fs::read(&path)
        .or_else(|_| {
            fs::create_dir_all(mermaid_cache_dir())
                .map_err(<_>::into)
                .and_then(|_| render_to_bytes(source, &path, appearance, executor))
        })
        .await?;

    // TODO: we're currently rendering this to png because usvg can't correctly parse
    // svg files generated by mermaid and produces trees without text elements in them.
    // This needs to be fixed upstream.
    Ok(Image::from_bytes(ImageFormat::Svg, bytes).into())
}

fn cache_path(source: &str, appearance: Appearance) -> PathBuf {
    let hash = Sha256::digest(source.as_bytes());
    mermaid_cache_dir().join(format!("{hash:x}-{}.svg", appearance.cache_file_affix()))
}

async fn render_to_bytes(
    source: SharedString,
    path: impl AsRef<OsStr>,
    appearance: Appearance,
    executor: BackgroundExecutor,
) -> anyhow::Result<Vec<u8>> {
    let (reader, mut writer) = std::io::pipe()?;

    let _writer_guard = executor.spawn(async move {
        if let Err(error) = writer.write_all(source.as_bytes()) {
            log::error!("failed to write to mermaid-cli stdin: {error}")
        }
    });

    let output = Command::new("npx")
        .args(["-y", "-p", "@mermaid-js/mermaid-cli", "mmdc"])
        .args(["--input", "-"])
        .arg("--output")
        .arg(path.as_ref())
        .args(["--theme", appearance.mermaid_theme()])
        .args(["--backgroundColor", "transparent"])
        .stdin(reader)
        .output()
        .await
        .context("Failed to run mermaid-cli (mmdc)")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let stderr = stderr.trim();
        log::warn!("mermaid-cli stderr: {stderr}");
        anyhow::bail!("Mermaid diagram rendering failed: {stderr}");
    }

    if !output.stderr.is_empty() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        log::debug!("mermaid-cli stderr: {}", stderr.trim());
    }

    Ok(fs::read(path.as_ref()).await?)
}
